Repository CMU-313/nodebb-f24-the-bots, pull requests merged in 2024-10, with the labels that each got.

#23 Added Backend Logic for Solving topics
  dump.rdb
  src/api/topics.js
  src/controllers/write/topics.js
  src/routes/write/topics.js
  src/topics/create.js
  src/topics/tools.js
  test/topics/events.js
Labels: enhancement

#26 Added sort function to sort topics by resolved/unresolved
  src/api/topics.js
Labels: enhancement

#28 UserGuide.md created for documentation
  UserGuide.md
Labels: documentation

#31 Installed and Ran the Dynamic Analysis Tool: Stryker Mutator
  .gitignore
  stryker.config.json
  stryker_output.txt
Labels: Analysis Tool

#32 Added complexity report
  .complexrc
  complexity-report.md
Labels: Analysis Tool

#37 Installed and Ran the Static Analysis Tool: JSHint
  .jshintrc
  jshint_output.txt
Labels: Analysis Tool

#38 Added JSHint to Github Workflows
  .github/workflows/jshint.yaml
  .gitignore
  .jshintrc
  dump.rdb
  package.json
  src/controllers/errors.js
  src/controllers/helpers.js
  src/request.js
Labels: Analysis Tool
